version: '3'

services:
    lt-chat-ms:
      image: cliffordun/lt-chat-ms
      command: python manage.py runserver 0:8000
      ports:
        - "8000:8000"
      depends_on:
        - lt-chat-db

  lt-chat-db:
      image: mongo:4
      ports:
        - "8001:27017"